"""
DPDP Schemas for PrivacyShield AI Compliance & Guardrails Engine.

Defines Pydantic models and dataclasses for:
- DPDPClause: Regulatory provisions and legal text chunks
- GuardrailDecision: Structured compliance decisions with audit trails
- ComplianceEvent: Input event schema for compliance validation
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class DPDPClause(BaseModel):
    """Represents a retrieved regulatory clause or rule from the DPDP corpus."""
    clause_id: str = Field(..., description="Unique regulatory identifier e.g. DPDP_ACT_SEC_8_5")
    title: str = Field(..., description="Short descriptive title of the regulation")
    text: str = Field(..., description="Statutory or rule text")
    source: str = Field(default="DPDP Act 2023", description="Source legal framework (Act or Rules)")
    tags: List[str] = Field(default_factory=list, description="Categorization tags")
    score: Optional[float] = Field(default=None, description="Retrieval similarity score")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context metadata")

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()


class ComplianceEvent(BaseModel):
    """Input payload representing an action/event requiring DPDP compliance verification."""
    event_type: str = Field(
        ...,
        description="Event category: CLOUD_TRANSMISSION, DEMASKING, RETENTION, CHILD_DATA, DOCUMENT_PROCESSING, AUDIT_LOG"
    )
    raw_pii_to_cloud: bool = Field(
        default=False,
        description="True if unmasked/raw PII is attempted to be sent to external cloud LLMs"
    )
    hitl_required: bool = Field(
        default=False,
        description="True if human-in-the-loop review was required for detected entities"
    )
    hitl_approved: bool = Field(
        default=False,
        description="True if human-in-the-loop review was completed and approved"
    )
    has_child_data: bool = Field(
        default=False,
        description="True if payload contains personal data belonging to minors (<18 years)"
    )
    child_consent_verified: bool = Field(
        default=False,
        description="True if verifiable parental/guardian consent is on file"
    )
    audit_written: bool = Field(
        default=True,
        description="True if immutable audit log entry was recorded"
    )
    document_id: Optional[str] = Field(default=None, description="Target document identifier")
    actor_id: Optional[str] = Field(default="usr_system", description="Identifier of the requesting user or service")
    purpose: Optional[str] = Field(default=None, description="Documented purpose for data access or processing")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Custom event metadata")

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()


class GuardrailDecision(BaseModel):
    """Comprehensive compliance decision output generated by the hybrid guardrails engine."""
    event_type: str = Field(..., description="Action/event evaluated")
    is_compliant: bool = Field(..., description="True if action satisfies all deterministic DPDP rules")
    blocked: bool = Field(..., description="True if the request must be blocked from proceeding")
    risk_level: str = Field(..., description="Assessed risk level: LOW, MEDIUM, HIGH, CRITICAL")
    triggered_rules: List[str] = Field(default_factory=list, description="Rules violated or triggered")
    passed_rules: List[str] = Field(default_factory=list, description="Rules successfully validated")
    retrieved_clauses: List[DPDPClause] = Field(default_factory=list, description="Referenced DPDP legal clauses")
    explanation: str = Field(..., description="Formal compliance reasoning generated by local Qwen or fallback")
    recommendations: List[str] = Field(default_factory=list, description="Actionable remediation steps")
    model_used: str = Field(default="local-qwen-explainer", description="Model engine used for explanation")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Audit and diagnostic metadata")

    def to_dict(self) -> Dict[str, Any]:
        return self.model_dump()
